// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ReadMySiteData, ReadMySiteResponse } from './types.gen';

export class MainService {
    /**
     * Read My Site
     * @param data The data for the request.
     * @param data.name
     * @returns MyBlogSite Successful Response
     * @throws ApiError
     */
    public static readMySite(data: ReadMySiteData): CancelablePromise<ReadMySiteResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/my-site/{name}',
            path: {
                name: data.name
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}