// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MyBlog = {
    id: number;
    title: string;
    comments?: Array<MyComment>;
    comment_count?: number;
};

export type MyBlogSite = {
    name: string;
    blogs?: Array<MyBlog>;
    comment_count?: number;
};

export type MyComment = {
    id: number;
    content: string;
    user_id: number;
    user?: User | null;
};

export type User = {
    id: number;
    name: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ReadMySiteData = {
    name: string;
};

export type ReadMySiteResponse = MyBlogSite;

export type $OpenApiTs = {
    '/my-site/{name}': {
        get: {
            req: ReadMySiteData;
            res: {
                /**
                 * Successful Response
                 */
                200: MyBlogSite;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};